# the yml file is commonly used as a configuration file, which defines a program/app's settings 
name: Express CI

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: alchemy
          POSTGRES_PASSWORD: alchemy
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run lint
      - run: npm runt test
        env:
          CI: true
          DATABASE_URL: postgres://alchemy:alchemy@postgres:5432/alchemy
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SALT_ROUNDS: ${{ secrets.SALT_ROUNDS }}
          COOKIE_NAME: ${{ secrets.COOKIE_NAME }}